name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows you to run it manually manually if needed

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Sync with upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: slopus/happy-cli # REPLACE THIS with the source repo!
          upstream_sync_branch: main # Or 'master', depending on the source
          target_sync_branch: main   # Your branch
          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # This is built-in, no setup needed
          test_mode: false
